name: Java CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Start server and run tests
        run: |
          # Запускаем сервер в фоне
          java -jar ./artifacts/app-mbank.jar &
          SERVER_PID=$!
          
          # Ждем запуска сервера
          sleep 10
          
          # Запускаем тесты
          ./gradlew test
          
          # Останавливаем сервер
          kill $SERVER_PID